using System.Numerics;
using System.Security.Cryptography;
using MathUtils;

namespace AsymmetricCryptography;

/// <summary>
/// Implementation of ElGamal.
/// </summary>
public class ElGamal {

    #region Record types

    /// <summary>
    /// ElGamal group parameters.
    /// </summary>
    /// <param name="P">The modulus for group operations.</param>
    /// <param name="Q">The order of the prime subgroup generated by <paramref name="G"/>.
    /// <param name="G">The generator for the group.</param>
    public sealed record Parameters(BigInteger P, BigInteger Q, BigInteger G);

    /// <summary>
    /// An ElGamal public key.
    /// </summary>
    /// <param name="H">The public value.</param>
    /// <param name="Parameters">The group parameters.</param>
    public sealed record PublicKey(BigInteger H, Parameters Parameters);

    /// <summary>
    /// An ElGamal private key.
    /// </summary>
    /// <param name="X">The private exponent.</param>
    /// <param name="Parameters">The group parameters.</param>
    public sealed record PrivateKey(BigInteger X, Parameters Parameters);

    /// <summary>
    /// An ElGamal key pair.
    /// </summary>
    /// <param name="PublicKey">The public key.</param>
    /// <param name="PrivateKey">The private key.</param>
    public sealed record KeyPair(PublicKey PublicKey, PrivateKey PrivateKey);

    #endregion

    #region Configuration

    /// <summary>
    /// The smallest modulus size, in bits, this implementation will generate or accept.
    /// </summary>
    public const int MinimumBitLength = 64;

    #endregion

    #region Members

    /// <summary>The modulus.</summary>
    private readonly BigInteger p;

    /// <summary>The prime order of the subgroup generated by <c>g</c>.</summary>
    private readonly BigInteger q;

    /// <summary>The generator.</summary>
    private readonly BigInteger g;

    /// <summary>The public key.</summary>
    private readonly BigInteger h;

    /// <summary>The private exponent.</summary>
    private readonly BigInteger x;

    /// <summary>Bit length of the prime order of the subgroup generated by <c>g</c>.</summary>
    private int ModulusBitLength { get => (int)p.GetBitLength(); }

    /// <summary>Byte length of the prime order of the subgroup generated by <c>g</c>.</summary>
    private int ModulusByteCount { get => (ModulusBitLength + 7) / 8; }

    #endregion

    #region Key retrieval

    /// <summary>Returns the parameters used by this instance.</summary>
    public Parameters GetParameters() => new Parameters(p, q, g);

    /// <summary>Returns the public key held by this instance.</summary>
    public PublicKey GetPublicKey() => new(h, GetParameters());

    /// <summary>Returns the private key held by this instance.</summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when this instance was constructed from a public key only.
    /// </exception>
    public PrivateKey GetPrivateKey() {
        if (x == default)
            throw new InvalidOperationException("No private key registered.");
        return new(x, GetParameters());
    }

    /// <summary>Returns the public/private key pair.</summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when this instance was constructed from a public key only.
    /// </exception>
    public KeyPair GetKeyPair() => new(GetPublicKey(), GetPrivateKey());

    #endregion

    #region Constructors

    /// <summary>
    /// Create an ElGamal instance. Generates parameters and key pair.
    /// </summary>
    /// <param name="bitLength">Modulus size in bits.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="bitLength"/> is below <see cref="MinimumBitLength"/>.</exception>
    /// <exception cref="ArgumentException"><paramref name="bitLength"/> is odd.</exception>
    public ElGamal(int bitLength) {
        (p, q, g) = GenerateParameters(bitLength);
        x = BigInteger.GetRandom(1, q - 1);
        h = g.ModExp(x, p);
    }

    /// <summary>
    /// Create an ElGamal instance. Generates a key pair with the given parameters.
    /// </summary>
    /// <param name="parameters">Group parameters to use.</param>
    /// <exception cref="ArgumentException"><paramref name="parameters"/> is malformed.</exception>
    public ElGamal(Parameters parameters) {
        ValidateParameters(parameters);

        (p, q, g) = (parameters.P, parameters.Q, parameters.G);
        x = BigInteger.GetRandom(1, q - 1);
        h = g.ModExp(x, p);
    }

    /// <summary>
    /// Wraps an existing public key. The resulting instance can encrypt and verify but not
    /// decrypt or sign.
    /// </summary>
    /// <param name="publicKey">The public key to use.</param>
    /// <exception cref="ArgumentOutOfRangeException">
    /// The modulus is not a positive odd integer of at least <see cref="MinimumBitLength"/> bits,
    /// or the exponent is not odd and in <c>[3, n)</c>.
    /// </exception>
    public ElGamal(PublicKey publicKey) {
        ValidateParameters(publicKey.Parameters);

        (p, q, g) = (publicKey.Parameters.P, publicKey.Parameters.Q, publicKey.Parameters.G);

        if (publicKey.H <= 1 || publicKey.H >= p)
            throw new ArgumentOutOfRangeException(nameof(publicKey), "Public key must be in (1, p).");
        if (publicKey.H.ModExp(q, p) != 1)
            throw new ArgumentException("Public key is not in the subgroup of order q.", nameof(publicKey));

        h = publicKey.H;
        x = default;
    }

    /// <summary>
    /// Wraps an existing key pair.
    /// </summary>
    /// <param name="keyPair">The key pair to adopt.</param>
    /// <exception cref="ArgumentOutOfRangeException">The private exponent is outside <c>[1, n)</c>, or the public half is malformed.</exception>
    /// <exception cref="ArgumentException">The private key does not match the public key.</exception>
    public ElGamal(KeyPair keyPair) : this(keyPair.PublicKey) {
        if (keyPair.PrivateKey.X < BigInteger.One || keyPair.PrivateKey.X >= q)
            throw new ArgumentOutOfRangeException(nameof(keyPair), "Private key must be in [1, q).");
        if (keyPair.PrivateKey.Parameters != keyPair.PublicKey.Parameters)
            throw new ArgumentException("Domain parameters do not match between public and private key.", nameof(keyPair));

        // Consistency probe
        if (g.ModExp(keyPair.PrivateKey.X, p) != h)
            throw new ArgumentException("Key pair is inconsistent: g^x mod p != y.", nameof(keyPair));

        x = keyPair.PrivateKey.X;
    }

    #endregion

    #region Encryption operations

    /// <summary>
    /// Encrypts a message using OAEP with SHA-256 and an empty label.
    /// </summary>
    /// <param name="plaintext">The message to encrypt.</param>
    /// <returns>A ciphertext <see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="ArgumentException">The plaintext is too long for the modulus.</exception>
    public byte[] Encrypt(ReadOnlySpan<byte> plaintext) => Encrypt(plaintext, new OAEPEncoder(HashAlgorithmName.SHA256));

    /// <summary>
    /// Encrypts a message using a caller-supplied OAEP encoder.
    /// </summary>
    /// <param name="plaintext">The message to encrypt.</param>
    /// <param name="encoder">The OAEP encoder supplying the hash, MGF1 hash, and label.</param>
    /// <returns>A ciphertext <see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="ArgumentException">The plaintext exceeds the encoder's capacity for this modulus.</exception>
    public byte[] Encrypt(ReadOnlySpan<byte> plaintext, OAEPEncoder encoder) {
        var maxLength = encoder.GetMaxMessageLength(ModulusByteCount);
        if (plaintext.Length > maxLength)
            throw new ArgumentException(
                $"Plaintext cannot exceed {maxLength} bytes when using the given OAEP encoder.",
                nameof(plaintext));

        var encodedPlaintext = encoder.Encode(plaintext, ModulusByteCount);
        var m = BigInteger.FromByteArray(encodedPlaintext);
        if (m >= p)
            throw new ArgumentException("Encoded plaintext is larger than p.", nameof(plaintext));

        var r = BigInteger.GetRandom(1, q - 1);
        var c1 = g.ModExp(r, p);
        var c2 = m.ModMultiply(h.ModExp(r, p), p);

        return [.. c1.ToByteArray(ModulusByteCount), .. c2.ToByteArray(ModulusByteCount)];
    }

    /// <summary>
    /// Decrypts a ciphertext produced with OAEP using SHA-256 and an empty label.
    /// </summary>
    /// <param name="ciphertext">The ciphertext, which must be <see cref="ModulusByteCount"/> bytes.</param>
    /// <returns>The recovered plaintext.</returns>
    /// <exception cref="InvalidOperationException">No private key is held.</exception>
    /// <exception cref="ArgumentException">The ciphertext is the wrong length, too large, or fails OAEP checks.</exception>
    public byte[] Decrypt(ReadOnlySpan<byte> ciphertext) => Decrypt(ciphertext, new OAEPEncoder(HashAlgorithmName.SHA256));

    /// <summary>
    /// Decrypts a ciphertext using a caller-supplied OAEP encoder.
    /// </summary>
    /// <param name="ciphertext">The ciphertext, which must be <see cref="ModulusByteCount"/> bytes.</param>
    /// <param name="encoder">An encoder configured identically to the one used to encrypt.</param>
    /// <returns>The recovered plaintext.</returns>
    /// <exception cref="InvalidOperationException">No private key is held.</exception>
    /// <exception cref="ArgumentException">The ciphertext is the wrong length, too large, or fails OAEP checks.</exception>
    public byte[] Decrypt(ReadOnlySpan<byte> ciphertext, OAEPEncoder encoder) {
        if (x == default)
            throw new InvalidOperationException("No private key set to decrypt the message.");
        if (ciphertext.Length != (2 * ModulusByteCount))
            throw new ArgumentException("Ciphertext length is not correct.", nameof(ciphertext));

        var c1 = BigInteger.FromByteArray(ciphertext[..ModulusByteCount]);
        var c2 = BigInteger.FromByteArray(ciphertext[ModulusByteCount..]);
        if (c1 >= p || c2 >= p)
            throw new ArgumentException("Ciphertext component is bigger than p.", nameof(ciphertext));

        var m = c2.ModMultiply(c1.ModExp(x, p).ModInverse(p), p);
        var encodedPlaintext = m.ToByteArray(ModulusByteCount);
        return encoder.Decode(encodedPlaintext);
    }

    #endregion

    #region Signing operations

    /// <summary>
    /// Signs data using ElGamal with SHA-256.
    /// </summary>
    /// <param name="data">The data to sign; it is hashed internally.</param>
    /// <returns>A signature 2*<see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="InvalidOperationException">No private key is available.</exception>
    public byte[] Sign(ReadOnlySpan<byte> data) => Sign(data, HashAlgorithmName.SHA256);

    /// <summary>
    /// Signs data using a caller-supplied hash algorithm.
    /// </summary>
    /// <param name="data">The data to sign; it is hashed internally.</param>
    /// <param name="hash">The hashing algorithm to use on the message.</param>
    /// <returns>A signature 2*<see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="InvalidOperationException">No private key is held, or the modulus is too small for this encoder.</exception>
    public byte[] Sign(ReadOnlySpan<byte> data, HashAlgorithmName hash) {
        if (x == default)
            throw new InvalidOperationException("No private key set to sign the message.");

        var digest = BigInteger.FromByteArray(CryptographicOperations.HashData(hash, data)).Mod(p);
        var k = BigInteger.GetRandom(1, q - 1);
        var r = g.ModExp(k, p);
        var s = digest.ModSubstract(x.ModMultiply(r, q), q).ModMultiply(k.ModInverse(q), q);

        return [.. r.ToByteArray(ModulusByteCount), .. s.ToByteArray(ModulusByteCount)];
    }

    /// <summary>
    /// Verifies an ElGamal signature using SHA-256.
    /// </summary>
    /// <param name="data">The data that was supposedly signed.</param>
    /// <param name="signature">The signature to check.</param>
    /// <returns><see langword="true"> if the signature is valid for this key.</returns>
    public bool Verify(ReadOnlySpan<byte> data, ReadOnlySpan<byte> signature) => Verify(data, signature, HashAlgorithmName.SHA256);

    /// <summary>
    /// Verifies an ElGamal signature using a caller-supplied hash function. Malformed input is reported
    /// as <c>false</c> rather than thrown, so callers need only one failure path.
    /// </summary>
    /// <param name="data">The data that was supposedly signed.</param>
    /// <param name="signature">The signature to check.</param>
    /// <param name="hash">An encoder configured identically to the one used to sign.</param>
    /// <returns><see langword="true"> if the signature is valid for this key.</returns>
    public bool Verify(ReadOnlySpan<byte> data, ReadOnlySpan<byte> signature, HashAlgorithmName hash) {
        if (signature.Length != (2 * ModulusByteCount)) return false;

        var r = BigInteger.FromByteArray(signature[..ModulusByteCount]);
        var s = BigInteger.FromByteArray(signature[ModulusByteCount..]);
        if (r >= p || s >= p)
            throw new ArgumentException("Signature component is bigger than p.", nameof(signature));

        var digest = BigInteger.FromByteArray(CryptographicOperations.HashData(hash, data)).Mod(p);
        var lhs = g.ModExp(digest, p);
        var rhs = h.ModExp(r, p).ModMultiply(r.ModExp(s, p), p);
        return lhs == rhs;
    }

    #endregion

    #region Helper functions

    // <summary>
    /// Generates group parameters of the desired length. 
    /// </summary>
    /// <param name="bitLength">Target bit length for <c>p</c>.</param>
    /// <returns>A validated <c>(p, q, g)</c> triple.</returns>
    private static Parameters GenerateParameters(int bitLength) {
        if (bitLength < MinimumBitLength)
            throw new ArgumentOutOfRangeException(nameof(bitLength),
                $"Security parameter must be at least {MinimumBitLength}.");

        // Start with q.
        var (p, q) = PrimeUtils.GetRandomSafePrime(bitLength);

        // Squaring any element of the group yields a quadratic residue, i.e. a member of the
        // unique subgroup of order q. Because q is prime, the only such member whose order is
        // not q is ±1, so rejecting ±1 leaves a genuine generator of that subgroup.
        BigInteger min = 2, max = p - 2;
        while (true) {
            var h = BigInteger.GetRandom(min, max);
            var g = h.ModExp(2, p);
            if (g != 1) {
                return new Parameters(p, q, g);
            }
        }
    }

    /// <summary>
    /// Rejects obviously malformed parameter sets.
    /// </summary>
    /// <param name="parameters">The parameters to check.</param>
    /// <exception cref="ArgumentException">The parameters cannot describe a valid safe-prime group.</exception>
    private static void ValidateParameters(Parameters parameters) {
        if (parameters.P < 5)
            throw new ArgumentException("Modulus must be a safe prime of at least 5.", nameof(parameters));
        if (parameters.Q < 2 || parameters.Q * 2 + 1 != parameters.P)
            throw new ArgumentException("SubgroupOrder must satisfy Modulus == 2 * SubgroupOrder + 1.", nameof(parameters));
        if (parameters.G < 2 || parameters.G > parameters.P - 2)
            throw new ArgumentException("Generator must lie in [2, Modulus - 2].", nameof(parameters));
    }

    #endregion

}
