using System.Numerics;
using System.Security.Cryptography;
using MathUtils;

namespace AsymmetricCryptography;

/// <summary>
/// Implementation of ElGamal.
/// </summary>
public class ElGamal {

    #region Record types

    /// <summary>
    /// ElGamal group parameters.
    /// </summary>
    /// <param name="P">The modulus for group operations.</param>
    /// <param name="Q">The order of the prime subgroup generated by <paramref name="G"/>.
    /// <param name="G">The generator for the group.</param>
    public sealed record Parameters(BigInteger P, BigInteger Q, BigInteger G);

    /// <summary>
    /// An ElGamal public key.
    /// </summary>
    /// <param name="H">The public value.</param>
    /// <param name="Parameters">The group parameters.</param>
    public sealed record PublicKey(BigInteger H, Parameters Parameters);

    /// <summary>
    /// An ElGamal private key.
    /// </summary>
    /// <param name="X">The private exponent.</param>
    /// <param name="Parameters">The group parameters.</param>
    public sealed record PrivateKey(BigInteger X, Parameters Parameters);

    /// <summary>
    /// An ElGamal key pair.
    /// </summary>
    /// <param name="PublicKey">The public key.</param>
    /// <param name="PrivateKey">The private key.</param>
    public sealed record KeyPair(PublicKey PublicKey, PrivateKey PrivateKey);

    #endregion

    #region Configuration

    /// <summary>
    /// The smallest modulus size, in bits, this implementation will generate or accept.
    /// </summary>
    public const int MinimumBitLength = 64;
    private Parameters Params;
    private PublicKey PUK = null;
    private PrivateKey PRK = null;
    private KeyPair KP;

    #endregion

    #region Key retrieval

    /// <summary>Returns the parameters used by this instance.</summary>
    public Parameters GetParameters() => Params;

    /// <summary>Returns the public key held by this instance.</summary>
    public PublicKey GetPublicKey() => PUK;

    /// <summary>Returns the private key held by this instance.</summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when this instance was constructed from a public key only.
    /// </exception>
    public PrivateKey GetPrivateKey() {
        if (PRK == null) throw new InvalidOperationException();
        return PRK;
    }

    /// <summary>Returns the public/private key pair.</summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when this instance was constructed from a public key only.
    /// </exception>
    public KeyPair GetKeyPair() {
        if (PRK == null) throw new InvalidOperationException();
        return KP;
    }

    #endregion

    #region Constructors

    /// <summary>
    /// Create an ElGamal instance. Generates parameters and key pair.
    /// </summary>
    /// <param name="bitLength">Modulus size in bits.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="bitLength"/> is below <see cref="MinimumBitLength"/>.</exception>
    /// <exception cref="ArgumentException"><paramref name="bitLength"/> is odd.</exception>
    public ElGamal(int bitLength) {
        if (bitLength < MinimumBitLength) throw new ArgumentOutOfRangeException();
        if ((bitLength & 1) == 1) throw new ArgumentException();

        (BigInteger p, BigInteger q) = PrimeUtils.GetRandomSafePrime(bitLength);
        BigInteger g;
        while (true) {
            g = BigInteger.GetRandom(2, p - 2).ModExp(2, p);
            if (g != BigInteger.One) break;
        }

        Params = new Parameters(p, q, g);

        BigInteger pre = BigInteger.GetRandom(1, q - 1);
        PRK = new PrivateKey(pre, Params);
        
        BigInteger pue = g.ModExp(pre, p);
        PUK = new PublicKey(pue, Params);

        KP = new KeyPair(PUK, PRK);
    }

    /// <summary>
    /// Create an ElGamal instance. Generates a key pair with the given parameters.
    /// </summary>
    /// <param name="parameters">Group parameters to use.</param>
    /// <exception cref="ArgumentException"><paramref name="parameters"/> is malformed.</exception>
    public ElGamal(Parameters parameters) {
        Params = parameters;
        if (Params.P < new BigInteger(5)) throw new ArgumentException();
        if (Params.Q < new BigInteger(2)) throw new ArgumentException();
        if (Params.Q * new BigInteger(2) + BigInteger.One != Params.P) throw new ArgumentException();
        if (Params.G < new BigInteger(2)) throw new ArgumentException();
        if (Params.G > Params.P - new BigInteger(2)) throw new ArgumentException();

        BigInteger pre = BigInteger.GetRandom(1, Params.Q - 1);
        PRK = new PrivateKey(pre, Params);
        
        BigInteger pue = Params.G.ModExp(pre, Params.P);
        PUK = new PublicKey(pue, Params);

        KP = new KeyPair(PUK, PRK);
    }

    /// <summary>
    /// Wraps an existing public key. The resulting instance can encrypt and verify but not
    /// decrypt or sign.
    /// </summary>
    /// <param name="publicKey">The public key to use.</param>
    /// <exception cref="ArgumentOutOfRangeException">
    /// The modulus is not a positive odd integer of at least <see cref="MinimumBitLength"/> bits,
    /// or the exponent is not odd and in <c>[3, n)</c>.
    /// </exception>
    public ElGamal(PublicKey publicKey) {
        Params = publicKey.Parameters;
        if (Params.P < new BigInteger(5)) throw new ArgumentException();
        if (Params.Q < new BigInteger(2)) throw new ArgumentException();
        if (Params.Q * new BigInteger(2) + BigInteger.One != Params.P) throw new ArgumentException();
        if (Params.G < new BigInteger(2)) throw new ArgumentException();
        if (Params.G > Params.P - new BigInteger(2)) throw new ArgumentException();

        if (publicKey.H <= BigInteger.One || publicKey.H >= Params.P) throw new ArgumentOutOfRangeException();
        if (publicKey.H.ModExp(Params.Q, Params.P) != BigInteger.One) throw new ArgumentException();

        PUK = publicKey;
    }

    /// <summary>
    /// Wraps an existing key pair.
    /// </summary>
    /// <param name="keyPair">The key pair to adopt.</param>
    /// <exception cref="ArgumentOutOfRangeException">The private exponent is outside <c>[1, n)</c>, or the public half is malformed.</exception>
    /// <exception cref="ArgumentException">The private key does not match the public key.</exception>
    public ElGamal(KeyPair keyPair) : this(keyPair.PublicKey) {
        if (keyPair.PrivateKey.Parameters != keyPair.PublicKey.Parameters) throw new ArgumentException();
        Params = keyPair.PublicKey.Parameters;
        if (Params.P < new BigInteger(5)) throw new ArgumentException();
        if (Params.Q < new BigInteger(2)) throw new ArgumentException();
        if (Params.Q * new BigInteger(2) + BigInteger.One != Params.P) throw new ArgumentException();
        if (Params.G < new BigInteger(2)) throw new ArgumentException();
        if (Params.G > Params.P - new BigInteger(2)) throw new ArgumentException();

        KP = keyPair;
        PUK = keyPair.PublicKey;
        PRK = keyPair.PrivateKey;

        if (PRK.X < BigInteger.One || PRK.X >= Params.Q) throw new ArgumentOutOfRangeException();
        if (Params.G.ModExp(PRK.X, Params.P) != PUK.H) throw new ArgumentException();
    }

    #endregion

    #region Encryption operations

    /// <summary>
    /// Encrypts a message using OAEP with SHA-256 and an empty label.
    /// </summary>
    /// <param name="plaintext">The message to encrypt.</param>
    /// <returns>A ciphertext <see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="ArgumentException">The plaintext is too long for the modulus.</exception>
    public byte[] Encrypt(ReadOnlySpan<byte> plaintext) => Encrypt(plaintext, new OAEPEncoder(HashAlgorithmName.SHA256));

    /// <summary>
    /// Encrypts a message using a caller-supplied OAEP encoder.
    /// </summary>
    /// <param name="plaintext">The message to encrypt.</param>
    /// <param name="encoder">The OAEP encoder supplying the hash, MGF1 hash, and label.</param>
    /// <returns>A ciphertext <see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="ArgumentException">The plaintext exceeds the encoder's capacity for this modulus.</exception>
    public byte[] Encrypt(ReadOnlySpan<byte> plaintext, OAEPEncoder encoder) {
        int modulusBytes = (int) (Params.P.GetBitLength() + 7) / 8;
        var maxLength = encoder.GetMaxMessageLength(modulusBytes);
        if (plaintext.Length > maxLength) throw new ArgumentException();

        byte[] encoded = encoder.Encode(plaintext, modulusBytes);
        BigInteger plainNum = BigInteger.FromByteArray(encoded);
        if (plainNum >= Params.P) throw new ArgumentException();

        BigInteger rand = BigInteger.GetRandom(BigInteger.One, Params.Q - BigInteger.One);
        byte[] cipher1 = Params.G.ModExp(rand, Params.P).ToByteArray(modulusBytes);
        byte[] cipher2 = plainNum.ModMultiply(PUK.H.ModExp(rand, Params.P), Params.P).ToByteArray(modulusBytes);

        byte[] output = new byte[modulusBytes * 2];
        for (int i = 0; i < modulusBytes; ++i) output[i] = cipher1[i];
        for (int i = 0; i < modulusBytes; ++i) output[i + modulusBytes] = cipher2[i];
        return output;
    }

    /// <summary>
    /// Decrypts a ciphertext produced with OAEP using SHA-256 and an empty label.
    /// </summary>
    /// <param name="ciphertext">The ciphertext, which must be <see cref="ModulusByteCount"/> bytes.</param>
    /// <returns>The recovered plaintext.</returns>
    /// <exception cref="InvalidOperationException">No private key is held.</exception>
    /// <exception cref="ArgumentException">The ciphertext is the wrong length, too large, or fails OAEP checks.</exception>
    public byte[] Decrypt(ReadOnlySpan<byte> ciphertext) => Decrypt(ciphertext, new OAEPEncoder(HashAlgorithmName.SHA256));

    /// <summary>
    /// Decrypts a ciphertext using a caller-supplied OAEP encoder.
    /// </summary>
    /// <param name="ciphertext">The ciphertext, which must be <see cref="ModulusByteCount"/> bytes.</param>
    /// <param name="encoder">An encoder configured identically to the one used to encrypt.</param>
    /// <returns>The recovered plaintext.</returns>
    /// <exception cref="InvalidOperationException">No private key is held.</exception>
    /// <exception cref="ArgumentException">The ciphertext is the wrong length, too large, or fails OAEP checks.</exception>
    public byte[] Decrypt(ReadOnlySpan<byte> ciphertext, OAEPEncoder encoder) {
        int modulusBytes = (int) (Params.P.GetBitLength() + 7) / 8;
        if (PRK == null) throw new InvalidOperationException();
        if (ciphertext.Length != modulusBytes * 2) throw new ArgumentException();

        byte[] cipher1 = ciphertext.Slice(0, modulusBytes).ToArray();
        byte[] cipher2 = ciphertext.Slice(modulusBytes).ToArray();
        BigInteger cipher1Num = BigInteger.FromByteArray(cipher1);
        BigInteger cipher2Num = BigInteger.FromByteArray(cipher2);
        if (cipher1Num >= Params.P || cipher2Num >= Params.P) throw new ArgumentException();

        BigInteger plainNum = cipher2Num.ModMultiply(cipher1Num.ModExp(PRK.X, Params.P).ModInverse(Params.P), Params.P);
        byte[] encoded = plainNum.ToByteArray(modulusBytes);
        return encoder.Decode(encoded);
    }

    #endregion

    #region Signing operations

    /// <summary>
    /// Signs data using ElGamal with SHA-256.
    /// </summary>
    /// <param name="data">The data to sign; it is hashed internally.</param>
    /// <returns>A signature 2*<see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="InvalidOperationException">No private key is available.</exception>
    public byte[] Sign(ReadOnlySpan<byte> data) => Sign(data, HashAlgorithmName.SHA256);

    /// <summary>
    /// Signs data using a caller-supplied hash algorithm.
    /// </summary>
    /// <param name="data">The data to sign; it is hashed internally.</param>
    /// <param name="hash">The hashing algorithm to use on the message.</param>
    /// <returns>A signature 2*<see cref="ModulusByteCount"/> bytes long.</returns>
    /// <exception cref="InvalidOperationException">No private key is held, or the modulus is too small for this encoder.</exception>
    public byte[] Sign(ReadOnlySpan<byte> data, HashAlgorithmName hash) {
        if (PRK == null) throw new InvalidOperationException();

        int modulusBytes = (int) (Params.P.GetBitLength() + 7) / 8;
        byte[] hashBytes = CryptographicOperations.HashData(hash, data);
        BigInteger hashNum = BigInteger.FromByteArray(hashBytes).Mod(Params.P);
        
        BigInteger rand = BigInteger.GetRandom(BigInteger.One, Params.Q - BigInteger.One);
        BigInteger cipher1Num = Params.G.ModExp(rand, Params.P);
        BigInteger invrand = rand.ModInverse(Params.Q);
        BigInteger cipher2Num = ((hashNum - (PRK.X * cipher1Num)) * invrand).Mod(Params.Q);
        byte[] cipher1 = cipher1Num.ToByteArray(modulusBytes);
        byte[] cipher2 = cipher2Num.ToByteArray(modulusBytes);
        
        byte[] output = new byte[modulusBytes * 2];
        for (int i = 0; i < modulusBytes; ++i) output[i] = cipher1[i];
        for (int i = 0; i < modulusBytes; ++i) output[i + modulusBytes] = cipher2[i];
        return output;
    }

    /// <summary>
    /// Verifies an ElGamal signature using SHA-256.
    /// </summary>
    /// <param name="data">The data that was supposedly signed.</param>
    /// <param name="signature">The signature to check.</param>
    /// <returns><see langword="true"> if the signature is valid for this key.</returns>
    public bool Verify(ReadOnlySpan<byte> data, ReadOnlySpan<byte> signature) => Verify(data, signature, HashAlgorithmName.SHA256);

    /// <summary>
    /// Verifies an ElGamal signature using a caller-supplied hash function. Malformed input is reported
    /// as <c>false</c> rather than thrown, so callers need only one failure path.
    /// </summary>
    /// <param name="data">The data that was supposedly signed.</param>
    /// <param name="signature">The signature to check.</param>
    /// <param name="hash">An encoder configured identically to the one used to sign.</param>
    /// <returns><see langword="true"> if the signature is valid for this key.</returns>
    public bool Verify(ReadOnlySpan<byte> data, ReadOnlySpan<byte> signature, HashAlgorithmName hash) {
        int modulusBytes = (int) (Params.P.GetBitLength() + 7) / 8;
        if (signature.Length != modulusBytes * 2) return false;

        byte[] cipher1 = signature.Slice(0, modulusBytes).ToArray();
        byte[] cipher2 = signature.Slice(modulusBytes).ToArray();
        BigInteger cipher1Num = BigInteger.FromByteArray(cipher1);
        BigInteger cipher2Num = BigInteger.FromByteArray(cipher2);
        if (cipher1Num >= Params.P || cipher2Num >= Params.P) throw new ArgumentException();

        BigInteger hashNum = BigInteger.FromByteArray(CryptographicOperations.HashData(hash, data)).Mod(Params.P);
        BigInteger expected = Params.G.ModExp(hashNum, Params.P);
        BigInteger actual = PUK.H.ModExp(cipher1Num, Params.P).ModMultiply(cipher1Num.ModExp(cipher2Num, Params.P), Params.P);

        return expected == actual;    
    }

    #endregion

}
