using System.Numerics;
using System.Security.Cryptography;
using Xunit;

namespace AsymmetricCryptography.Tests;

/// <summary>
/// Shared, expensive-to-generate state for <see cref="DiffieHellmanTests"/>. xUnit constructs
/// one instance of a class implementing <see cref="IClassFixture{TFixture}"/> per test class run
/// and shares it across every test in that class, so the safe-prime group generated here (and the
/// two key pairs derived from it) is only computed once instead of once per test.
/// </summary>
public class DiffieHellmanFixture {

    /// <summary>A minimum-size group, generated once for the whole test class.</summary>
    public DiffieHellman.Parameters Parameters { get; }

    /// <summary>Alice's key pair, using <see cref="Parameters"/>.</summary>
    public DiffieHellman Alice { get; }

    /// <summary>Bob's key pair, using <see cref="Parameters"/>.</summary>
    public DiffieHellman Bob { get; }

    /// <summary>
    /// A group element that is a member of the full group but NOT of the prime-order subgroup
    /// generated by <see cref="Parameters"/>.Generator. Used to exercise the "wrong order"
    /// validation path in <see cref="DiffieHellman.ComputeSharedValue"/>. For a safe-prime group
    /// (order p-1 = 2q), any element that is not a quadratic residue and not p-1 itself has order
    /// 2q, so raising it to the q-th power will not yield 1.
    /// </summary>
    public BigInteger WrongOrderElement { get; }

    public DiffieHellmanFixture() {
        Parameters = new DiffieHellman(DiffieHellman.MinimumBitLength).GetParameters();
        Alice = new DiffieHellman(Parameters);
        Bob = new DiffieHellman(Parameters);

        for (var candidate = new BigInteger(2); ; candidate++) {
            if (BigInteger.ModPow(candidate, Parameters.Order, Parameters.Modulus) != BigInteger.One) {
                WrongOrderElement = candidate;
                break;
            }
        }
    }
}

public class DiffieHellmanTests : IClassFixture<DiffieHellmanFixture> {

    private readonly DiffieHellmanFixture fixture;

    public DiffieHellmanTests(DiffieHellmanFixture fixture) => this.fixture = fixture;

    #region Parameter generation

    [Fact]
    public void GenerateParameters_BelowMinimumBitLength_Throws() {
        Assert.Throws<ArgumentOutOfRangeException>(
            () => new DiffieHellman(DiffieHellman.MinimumBitLength - 1).GetParameters());
    }

    [Theory]
    [InlineData(32)]
    [InlineData(40)]
    public void GenerateParameters_ProducesValidSafePrimeGroup(int bitLength) {
        var parameters = new DiffieHellman(bitLength).GetParameters();

        // Modulus = 2 * Order + 1 (safe prime relation).
        Assert.Equal(parameters.Modulus, parameters.Order * 2 + 1);

        // Generator lies in the valid range and has the stated order.
        Assert.InRange(parameters.Generator, 2, parameters.Modulus - 2);
        Assert.Equal(BigInteger.One, BigInteger.ModPow(parameters.Generator, parameters.Order, parameters.Modulus));
        Assert.NotEqual(BigInteger.One, parameters.Generator);
    }

    #endregion

    #region Constructor validation

    [Fact]
    public void Constructor_BitLengthBelowMinimum_Throws() {
        Assert.Throws<ArgumentOutOfRangeException>(() => new DiffieHellman(DiffieHellman.MinimumBitLength - 1));
    }

    [Fact]
    public void Constructor_WithGeneratedParameters_ProducesConsistentPublicKey() {
        var dh = new DiffieHellman(fixture.Parameters);

        // Public key must lie in the subgroup of the stated order.
        var pub = dh.GetPublicValue();
        Assert.InRange(pub, 1, fixture.Parameters.Modulus - 1);
        Assert.Equal(BigInteger.One, BigInteger.ModPow(pub, fixture.Parameters.Order, fixture.Parameters.Modulus));
    }

    [Fact]
    public void Constructor_ModulusTooSmall_Throws() {
        var bad = new DiffieHellman.Parameters(4, 2, 1);
        Assert.Throws<ArgumentException>(() => new DiffieHellman(bad));
    }

    [Fact]
    public void Constructor_OrderDoesNotMatchModulus_Throws() {
        // Modulus should equal 2*Order + 1; deliberately break that relation.
        var bad = new DiffieHellman.Parameters(fixture.Parameters.Modulus, fixture.Parameters.Generator, fixture.Parameters.Order + 2);
        Assert.Throws<ArgumentException>(() => new DiffieHellman(bad));
    }

    [Fact]
    public void Constructor_GeneratorOutOfRange_Throws() {
        var tooLarge = fixture.Parameters with { Generator = fixture.Parameters.Modulus - 1 };
        Assert.Throws<ArgumentException>(() => new DiffieHellman(tooLarge));

        var tooSmall = fixture.Parameters with { Generator = 1 };
        Assert.Throws<ArgumentException>(() => new DiffieHellman(tooSmall));
    }

    [Fact]
    public void GetParameters_ReturnsParametersUsedToConstruct() {
        var dh = new DiffieHellman(fixture.Parameters);
        Assert.Equal(fixture.Parameters, dh.GetParameters());
    }

    #endregion

    #region Key agreement

    [Fact]
    public void ComputeSharedValue_BothParties_AgreeOnSameValue() {
        var aliceShared = fixture.Alice.ComputeSharedValue(fixture.Bob.GetPublicValue());
        var bobShared = fixture.Bob.ComputeSharedValue(fixture.Alice.GetPublicValue());

        Assert.Equal(aliceShared, bobShared);
    }

    [Fact]
    public void ComputeSharedKey_BothParties_AgreeOnSameBytes() {
        var aliceKey = fixture.Alice.ComputeSharedKey(fixture.Bob.GetPublicValue(), 32);
        var bobKey = fixture.Bob.ComputeSharedKey(fixture.Alice.GetPublicValue(), 32);

        Assert.Equal(aliceKey, bobKey);
    }

    [Fact]
    public void ComputeSharedKey_RequestedLength_IsHonored() {
        var key = fixture.Alice.ComputeSharedKey(fixture.Bob.GetPublicValue(), 48);
        Assert.Equal(48, key.Length);
    }

    [Fact]
    public void ComputeSharedKey_ZeroOrNegativeByteCount_Throws() {
        Assert.Throws<ArgumentOutOfRangeException>(() => fixture.Alice.ComputeSharedKey(fixture.Bob.GetPublicValue(), 0));
        Assert.Throws<ArgumentOutOfRangeException>(() => fixture.Alice.ComputeSharedKey(fixture.Bob.GetPublicValue(), -1));
    }

    /// <summary>
    /// Cross-checks the key-derivation step against .NET's own HKDF implementation
    /// (<see cref="System.Security.Cryptography.HKDF"/>) rather than trusting this library's
    /// internal call to it. The raw shared value is recomputed independently via
    /// <see cref="BigInteger.ModPow"/> and fed through the framework's HKDF-SHA512 as the
    /// implementation documents; the two derived keys must match byte-for-byte.
    /// </summary>
    [Fact]
    public void ComputeSharedKey_MatchesIndependentHkdfComputation() {
        var bobPublic = fixture.Bob.GetPublicValue();
        var alicePublic = fixture.Alice.GetPublicValue();

        var actual = fixture.Alice.ComputeSharedKey(bobPublic, 32);

        // Recompute the raw shared value from public information plus Bob's shared value
        // (which Bob can independently confirm equals what Alice computes -- see the
        // agreement test above), then derive the key using the framework's HKDF directly.
        var rawShared = fixture.Bob.ComputeSharedValue(alicePublic);
        var byteLength = ((int)fixture.Parameters.Order.GetBitLength() + 7) / 8;
        var rawSharedBytes = rawShared.ToByteArray(byteLength);

        var expected = HKDF.DeriveKey(HashAlgorithmName.SHA512, rawSharedBytes, 32);

        Assert.Equal(expected, actual);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    public void ComputeSharedValue_ValueBelowRange_Throws(int value) {
        Assert.Throws<ArgumentOutOfRangeException>(() => fixture.Alice.ComputeSharedValue(value));
    }

    [Fact]
    public void ComputeSharedValue_ValueAboveRange_Throws() {
        Assert.Throws<ArgumentOutOfRangeException>(
            () => fixture.Alice.ComputeSharedValue(fixture.Parameters.Modulus - 1));
        Assert.Throws<ArgumentOutOfRangeException>(
            () => fixture.Alice.ComputeSharedValue(fixture.Parameters.Modulus));
    }

    [Fact]
    public void ComputeSharedValue_WrongOrderElement_Throws() {
        Assert.Throws<ArgumentOutOfRangeException>(
            () => fixture.Alice.ComputeSharedValue(fixture.WrongOrderElement));
    }

    #endregion
}
