using System.Security.Cryptography;
using Xunit;

namespace SymmetricEncryption.Tests;

/// <summary>
/// Verifies <see cref="AES.Encrypt"/> and <see cref="AES.Decrypt"/> in every supported
/// <see cref="BlockMode"/> against <see cref="System.Security.Cryptography.Aes"/>.
/// </summary>
/// <remarks>
/// <para>
/// ECB and CBC are compared against the platform's one-shot <c>EncryptEcb</c>/<c>EncryptCbc</c> APIs with
/// <see cref="PaddingMode.PKCS7"/>, matching this implementation, which always pads (a full block of
/// padding is appended when the message is already block aligned).
/// </para>
/// <para>
/// The platform does not implement CTR, so the reference keystream is generated by enciphering successive
/// counter blocks with the platform's ECB primitive (<see cref="PaddingMode.None"/>) and XORing, exactly as
/// SP 800-38A &#167;6.5 defines. The reference counter is incremented over the full 16 bytes, big endian,
/// and is allowed to wrap to zero, which reproduces this implementation's documented and intentional
/// wraparound behavior rather than asserting a different one.
/// </para>
/// </remarks>
public sealed class AESTests {

    /// <summary>Key sizes in bytes for AES-128, AES-192, and AES-256.</summary>
    private static readonly int[] KeyLengths = [16, 24, 32];

    /// <summary>
    /// Message lengths chosen to cover the empty message, sub-block, exactly aligned, and partial trailing
    /// block cases on both sides of the block boundary.
    /// </summary>
    private static readonly int[] MessageLengths = [0, 1, 15, 16, 17, 31, 32, 33, 64, 100, 255, 1024];

    /// <summary>All supported block modes.</summary>
    private static readonly BlockMode[] Modes = [BlockMode.ECB, BlockMode.CBC, BlockMode.CTR];

    /// <summary>The cross product of <see cref="Modes"/>, <see cref="KeyLengths"/>, and <see cref="MessageLengths"/>.</summary>
    public static TheoryData<BlockMode, int, int> ModeKeyAndMessageLengths {
        get {
            var data = new TheoryData<BlockMode, int, int>();
            foreach (var mode in Modes)
                foreach (var keyLength in KeyLengths)
                    foreach (var messageLength in MessageLengths)
                        data.Add(mode, keyLength, messageLength);
            return data;
        }
    }

    /// <summary>The cross product of <see cref="Modes"/> and <see cref="KeyLengths"/>.</summary>
    public static TheoryData<BlockMode, int> ModeAndKeyLengths {
        get {
            var data = new TheoryData<BlockMode, int>();
            foreach (var mode in Modes)
                foreach (var keyLength in KeyLengths)
                    data.Add(mode, keyLength);
            return data;
        }
    }

    /// <summary>Key sizes in bytes, one per test case.</summary>
    public static TheoryData<int> KeyLengthData => new(KeyLengths);

    #region Encrypt matches System.Security.Cryptography

    [Theory]
    [MemberData(nameof(ModeKeyAndMessageLengths))]
    public void Encrypt_MatchesSystemCryptography(BlockMode mode, int keyLength, int messageLength) {
        var (key, iv, plaintext) = Inputs(keyLength, messageLength);

        var actual = new AES(key).Encrypt(plaintext, mode, iv);
        var expected = ReferenceEncrypt(key, iv, plaintext, mode);

        Assert.Equal(expected, actual);
    }

    [Theory]
    [MemberData(nameof(ModeKeyAndMessageLengths))]
    public void Decrypt_MatchesSystemCryptography(BlockMode mode, int keyLength, int messageLength) {
        var (key, iv, plaintext) = Inputs(keyLength, messageLength);

        // Start from a reference ciphertext so decryption is validated independently of this Encrypt.
        var ciphertext = ReferenceEncrypt(key, iv, plaintext, mode);
        var actual = new AES(key).Decrypt(ciphertext, mode, iv);

        Assert.Equal(plaintext, actual);
        Assert.Equal(ReferenceDecrypt(key, iv, ciphertext, mode), actual);
    }

    [Theory]
    [MemberData(nameof(ModeKeyAndMessageLengths))]
    public void EncryptThenDecrypt_RoundTrips(BlockMode mode, int keyLength, int messageLength) {
        var (key, iv, plaintext) = Inputs(keyLength, messageLength);
        var aes = new AES(key);

        var ciphertext = aes.Encrypt(plaintext, mode, iv);
        var recovered = aes.Decrypt(ciphertext, mode, iv);

        Assert.Equal(plaintext, recovered);
    }

    [Theory]
    [MemberData(nameof(ModeAndKeyLengths))]
    public void Encrypt_IsDeterministicAndStateless(BlockMode mode, int keyLength) {
        var (key, iv, plaintext) = Inputs(keyLength, 100);
        var aes = new AES(key);

        var first = aes.Encrypt(plaintext, mode, iv);
        // Encrypt and decrypt unrelated data in between to prove no state carries over between calls.
        aes.Encrypt(new byte[64], mode, iv);
        aes.Decrypt(first, mode, iv);
        var second = aes.Encrypt(plaintext, mode, iv);

        Assert.Equal(first, second);
    }

    #endregion

    #region Mode specific structure

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptECB_ProducesIdenticalCiphertextForIdenticalPlaintextBlocks(int keyLength) {
        var (key, _, _) = Inputs(keyLength, 0);
        var plaintext = Enumerable.Repeat<byte>(0x5a, 48).ToArray();

        var ciphertext = new AES(key).Encrypt(plaintext, BlockMode.ECB);

        Assert.Equal(64, ciphertext.Length);  // 48 bytes plus a full padding block.
        Assert.Equal(ciphertext[..16], ciphertext[16..32]);
        Assert.Equal(ciphertext[..16], ciphertext[32..48]);
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptECB_IgnoresTheIvOrCounterArgument(int keyLength) {
        var (key, iv, plaintext) = Inputs(keyLength, 100);
        var aes = new AES(key);

        var withoutIv = aes.Encrypt(plaintext, BlockMode.ECB);
        var withIv = aes.Encrypt(plaintext, BlockMode.ECB, iv);

        Assert.Equal(withoutIv, withIv);
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptCBC_DiffersForDifferentIvs(int keyLength) {
        var (key, iv, plaintext) = Inputs(keyLength, 100);
        var otherIv = iv.ToArray();
        otherIv[0] ^= 0xff;
        var aes = new AES(key);

        Assert.NotEqual(aes.Encrypt(plaintext, BlockMode.CBC, iv), aes.Encrypt(plaintext, BlockMode.CBC, otherIv));
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptCTR_DoesNotPadAndIsSelfInverse(int keyLength) {
        var (key, counter, plaintext) = Inputs(keyLength, 100);
        var aes = new AES(key);

        var ciphertext = aes.Encrypt(plaintext, BlockMode.CTR, counter);

        Assert.Equal(plaintext.Length, ciphertext.Length);
        // Encrypt and Decrypt are the same operation in CTR mode.
        Assert.Equal(plaintext, aes.Encrypt(ciphertext, BlockMode.CTR, counter));
        Assert.Equal(ciphertext, aes.Decrypt(plaintext, BlockMode.CTR, counter));
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptCTR_KeystreamIsTheEcbEnciphermentOfSuccessiveCounters(int keyLength) {
        var (key, counter, _) = Inputs(keyLength, 0);
        var zeros = new byte[3 * AES.BlockSize];

        // XORing zeros with the keystream exposes the keystream itself.
        var keystream = new AES(key).Encrypt(zeros, BlockMode.CTR, counter);

        Assert.Equal(ReferenceKeystream(key, counter, zeros.Length), keystream);
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptCTR_IncrementsTheCounterAcrossEveryByteBoundary(int keyLength) {
        var (key, _, _) = Inputs(keyLength, 0);
        // 0x...00ff and 0x...ffff force carries out of the low byte and out of the low two bytes.
        foreach (var counter in new[] { CounterFrom(0x00ff), CounterFrom(0xffff), CounterFrom(0xfffe) }) {
            var keystream = new AES(key).Encrypt(new byte[4 * AES.BlockSize], BlockMode.CTR, counter);
            Assert.Equal(ReferenceKeystream(key, counter, keystream.Length), keystream);
        }
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void EncryptCTR_WrapsTheCounterToZeroAfterTheAllOnesBlock(int keyLength) {
        // This documents the known, intentional wraparound: the counter is a 128-bit big-endian value that
        // rolls over to zero, so a long enough message reuses keystream. The behavior is asserted, not fixed.
        var (key, _, _) = Inputs(keyLength, 0);
        var allOnes = Enumerable.Repeat<byte>(0xff, AES.BlockSize).ToArray();

        var keystream = new AES(key).Encrypt(new byte[2 * AES.BlockSize], BlockMode.CTR, allOnes);

        using var reference = Aes.Create();
        reference.Key = key;
        var expectedFirst = reference.EncryptEcb(allOnes, PaddingMode.None);
        var expectedSecond = reference.EncryptEcb(new byte[AES.BlockSize], PaddingMode.None);

        Assert.Equal(expectedFirst, keystream[..AES.BlockSize]);
        Assert.Equal(expectedSecond, keystream[AES.BlockSize..]);
    }

    #endregion

    #region Padding

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void Encrypt_AppendsAFullBlockOfPaddingWhenTheMessageIsBlockAligned(int keyLength) {
        var (key, iv, plaintext) = Inputs(keyLength, 32);
        var aes = new AES(key);

        Assert.Equal(48, aes.Encrypt(plaintext, BlockMode.ECB).Length);
        Assert.Equal(48, aes.Encrypt(plaintext, BlockMode.CBC, iv).Length);
    }

    [Theory]
    [MemberData(nameof(ModeAndKeyLengths))]
    public void Encrypt_PadsToTheSameLengthAsSystemCryptography(BlockMode mode, int keyLength) {
        foreach (var messageLength in MessageLengths) {
            var (key, iv, plaintext) = Inputs(keyLength, messageLength);
            var expected = ReferenceEncrypt(key, iv, plaintext, mode).Length;

            Assert.Equal(expected, new AES(key).Encrypt(plaintext, mode, iv).Length);
        }
    }

    [Theory]
    [MemberData(nameof(KeyLengthData))]
    public void Decrypt_RejectsMalformedPadding(int keyLength) {
        var (key, iv, _) = Inputs(keyLength, 0);
        using var reference = Aes.Create();
        reference.Key = key;

        // A block whose final byte is 0x00 and one whose final byte exceeds the block size are both invalid.
        foreach (var finalByte in new byte[] { 0x00, 0x11 }) {
            var block = new byte[AES.BlockSize];
            block[^1] = finalByte;

            var ecb = reference.EncryptEcb(block, PaddingMode.None);
            var cbc = reference.EncryptCbc(block, iv, PaddingMode.None);

            Assert.Throws<ArgumentException>(() => new AES(key).Decrypt(ecb, BlockMode.ECB));
            Assert.Throws<ArgumentException>(() => new AES(key).Decrypt(cbc, BlockMode.CBC, iv));
        }

        // Padding of 0x02 that is not repeated is also invalid.
        var inconsistent = new byte[AES.BlockSize];
        (inconsistent[^2], inconsistent[^1]) = ((byte)0x03, (byte)0x02);
        var inconsistentEcb = reference.EncryptEcb(inconsistent, PaddingMode.None);

        Assert.Throws<ArgumentException>(() => new AES(key).Decrypt(inconsistentEcb, BlockMode.ECB));
    }

    #endregion

    #region Argument validation

    [Theory]
    [InlineData(BlockMode.CBC)]
    [InlineData(BlockMode.CTR)]
    public void Encrypt_RejectsAnIvOrCounterThatIsNot16Bytes(BlockMode mode) {
        var aes = new AES(new byte[16]);
        var plaintext = new byte[32];

        foreach (var length in new[] { 0, 1, 8, 15, 17, 32 }) {
            var ivOrCounter = new byte[length];
            Assert.Throws<ArgumentException>(() => aes.Encrypt(plaintext, mode, ivOrCounter));
            Assert.Throws<ArgumentException>(() => aes.Decrypt(plaintext, mode, ivOrCounter));
        }

        // Omitting the argument entirely is the same as passing an empty span.
        Assert.Throws<ArgumentException>(() => aes.Encrypt(plaintext, mode));
    }

    [Theory]
    [InlineData(BlockMode.ECB)]
    [InlineData(BlockMode.CBC)]
    public void Decrypt_RejectsCiphertextThatIsNotANonEmptyMultipleOfTheBlockSize(BlockMode mode) {
        var aes = new AES(new byte[16]);
        var iv = new byte[16];

        foreach (var length in new[] { 0, 1, 15, 17, 31, 33 })
            Assert.Throws<ArgumentException>(() => aes.Decrypt(new byte[length], mode, iv));
    }

    [Fact]
    public void EncryptAndDecrypt_RejectAnUnrecognizedMode() {
        var aes = new AES(new byte[16]);
        var mode = (BlockMode)0x7f;

        Assert.Throws<ArgumentOutOfRangeException>(() => aes.Encrypt(new byte[16], mode, new byte[16]));
        Assert.Throws<ArgumentOutOfRangeException>(() => aes.Decrypt(new byte[16], mode, new byte[16]));
    }

    #endregion

    #region Reference implementation

    /// <summary>
    /// Builds a deterministic key, IV/counter, and message for a test case.
    /// </summary>
    /// <param name="keyLength">The key size in bytes.</param>
    /// <param name="messageLength">The message size in bytes.</param>
    /// <returns>The generated inputs.</returns>
    private static (byte[] Key, byte[] Iv, byte[] Plaintext) Inputs(int keyLength, int messageLength) {
        // Seeded so failures are reproducible; the values themselves are arbitrary.
        var random = new Random(keyLength * 1_000 + messageLength);
        var key = new byte[keyLength];
        var iv = new byte[AES.BlockSize];
        var plaintext = new byte[messageLength];
        random.NextBytes(key);
        random.NextBytes(iv);
        random.NextBytes(plaintext);
        return (key, iv, plaintext);
    }

    /// <summary>
    /// Encrypts using <see cref="System.Security.Cryptography.Aes"/> as the ground truth.
    /// </summary>
    /// <param name="key">The cipher key.</param>
    /// <param name="ivOrCounter">The CBC IV or the initial CTR counter block.</param>
    /// <param name="plaintext">The message to encrypt.</param>
    /// <param name="mode">The block cipher mode.</param>
    /// <returns>The reference ciphertext.</returns>
    private static byte[] ReferenceEncrypt(byte[] key, byte[] ivOrCounter, byte[] plaintext, BlockMode mode) {
        using var reference = Aes.Create();
        reference.Key = key;
        return mode switch {
            BlockMode.ECB => reference.EncryptEcb(plaintext, PaddingMode.PKCS7),
            BlockMode.CBC => reference.EncryptCbc(plaintext, ivOrCounter, PaddingMode.PKCS7),
            BlockMode.CTR => Xor(plaintext, ReferenceKeystream(key, ivOrCounter, plaintext.Length)),
            _ => throw new ArgumentOutOfRangeException(nameof(mode))
        };
    }

    /// <summary>
    /// Decrypts using <see cref="System.Security.Cryptography.Aes"/> as the ground truth.
    /// </summary>
    /// <param name="key">The cipher key.</param>
    /// <param name="ivOrCounter">The CBC IV or the initial CTR counter block.</param>
    /// <param name="ciphertext">The ciphertext to decrypt.</param>
    /// <param name="mode">The block cipher mode.</param>
    /// <returns>The reference plaintext.</returns>
    private static byte[] ReferenceDecrypt(byte[] key, byte[] ivOrCounter, byte[] ciphertext, BlockMode mode) {
        using var reference = Aes.Create();
        reference.Key = key;
        return mode switch {
            BlockMode.ECB => reference.DecryptEcb(ciphertext, PaddingMode.PKCS7),
            BlockMode.CBC => reference.DecryptCbc(ciphertext, ivOrCounter, PaddingMode.PKCS7),
            BlockMode.CTR => Xor(ciphertext, ReferenceKeystream(key, ivOrCounter, ciphertext.Length)),
            _ => throw new ArgumentOutOfRangeException(nameof(mode))
        };
    }

    /// <summary>
    /// Generates a CTR keystream of the requested length by enciphering successive counter blocks with the
    /// platform's ECB primitive, per SP 800-38A &#167;6.5.
    /// </summary>
    /// <param name="key">The cipher key.</param>
    /// <param name="counter">The initial counter block.</param>
    /// <param name="length">The number of keystream bytes required.</param>
    /// <returns>The keystream.</returns>
    /// <remarks>
    /// The counter spans all 16 bytes, is treated as a big-endian integer, and wraps to zero on overflow,
    /// matching the implementation under test.
    /// </remarks>
    private static byte[] ReferenceKeystream(byte[] key, byte[] counter, int length) {
        var blocks = (length + AES.BlockSize - 1) / AES.BlockSize;
        var counterBlocks = new byte[blocks * AES.BlockSize];
        var current = counter.ToArray();

        for (var block = 0; block < blocks; block++) {
            current.CopyTo(counterBlocks, block * AES.BlockSize);
            for (var i = current.Length - 1; i >= 0 && ++current[i] == 0; i--) { }
        }

        using var reference = Aes.Create();
        reference.Key = key;
        return reference.EncryptEcb(counterBlocks, PaddingMode.None)[..length];
    }

    /// <summary>
    /// XORs <paramref name="data"/> with the leading bytes of <paramref name="keystream"/>.
    /// </summary>
    /// <param name="data">The data to mask.</param>
    /// <param name="keystream">The keystream, at least as long as <paramref name="data"/>.</param>
    /// <returns>The masked data.</returns>
    private static byte[] Xor(byte[] data, byte[] keystream) {
        var result = new byte[data.Length];
        for (var i = 0; i < data.Length; i++)
            result[i] = (byte)(data[i] ^ keystream[i]);
        return result;
    }

    /// <summary>
    /// Builds a counter block whose low 16 bits are <paramref name="low"/> and whose other bytes are zero.
    /// </summary>
    /// <param name="low">The value of the low two bytes.</param>
    /// <returns>The counter block.</returns>
    private static byte[] CounterFrom(int low) {
        var counter = new byte[AES.BlockSize];
        counter[^2] = (byte)(low >> 8);
        counter[^1] = (byte)low;
        return counter;
    }

    #endregion

}
